version: '3.4'

services:
  php-fpm:
    build:
      context: api/docker/php
    volumes:
      - ./api:/srv/api:rw
    ports:
      - "9000:9000"
    depends_on:
      - db

  nginx:
    build:
      context: api/docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./api:/srv/api:ro
      - ./api/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./api/docker/nginx/Sites:/etc/nginx/sites-available
    depends_on:
      - php-fpm
    links:
      - php-fpm

  db:
    build:
      context: api/docker/db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=product_db
      - MYSQL_ROOT_PASSWORD=root
  app:
    build:
      context: app
    volumes:
      - ./app:/usr/src/app:rw
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    command: /bin/sh -c "npm run serve"
